#!/usr/bin/bash
##-------------------------------------------------------
##                  gestion des versions 
##-------------------------------------------------------
# Nom du fichier contenant la version
fichier_version="version.txt"

# Fonction pour incrémenter la version
increment_version() {
    local major
    local minor
    local build

    IFS='.' read -r major minor build<<< "$version"

    if [ "$1" == "major" ]; then
        major=$((major + 1))
        minor=0
        build=0
    elif [ "$1" == "minor" ]; then
        minor=$((minor + 1))
    elif [ "$1" == "build" ]; then
        build=$((build + 1))
    else
        echo "Usage: $0 [major|minor|build]"
        
    fi

    version="$major.$minor.$build"
}

# Vérification du nombre d'arguments
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 [major|minor|build]"
    
fi

# Lecture de la version actuelle depuis le fichier
if [ -e "$fichier_version" ]; then
    version=$(cat "$fichier_version")
else
    # Si le fichier n'existe pas, utilisez une version par défaut
    version="1.0.0"
fi

# Incrémentation de la version en fonction du paramètre fourni
increment_version "$1"

# Enregistrement de la nouvelle version dans le fichier
echo "$version" > "$fichier_version"

# Affichage de la nouvelle version
echo "Version : $version"

##-------------------------------------------------------
##                  passage c to html
##-------------------------------------------------------



##création du volume sae103
docker volume create sae103

## lancement de transformation c to html
docker run -d --name sae103-forever -v sae103:/work clock

echo '' > fic_c
for fic in src/*.c
do
    echo $fic >> fic_c
    docker cp $fic sae103-forever:/work
done
cat fic_c

docker cp fic_c sae103-forever:/work
#docker run -d --name conteneursae103 -v sae103:/work clock
docker cp gendoc-tech.php sae103-forever:/work
docker cp gendoc-user.php sae103-forever:/work
docker cp bash_fic_c sae103-forever:/work
docker cp bash_fic_c sae103-forever:/work


docker run --rm -v sae103:/work sae103-php php gendoc-tech.php > DOC_TECH-$version.html
#docker run --rm -v sae103:/work sae103-php php gendoc-user.php

docker cp DOC_TECH-$version.html sae103-forever:/work


##-------------------------------------------------------
##                  passage html to pdf
##-------------------------------------------------------



# ##passage des docs vers pdf
docker run --rm -v sae103:/work sae103-html2pdf "html2pdf DOC_TECH-$version.html DOC_TECH-$version.pdf"
##docker run --rm -v sae103:/work sae103-html2pdf "html2pdf DOC_USER-$version.html DOC_USER-$version.pdf"

# # ##création du dossier gz
 docker run --rm -v sae103:/work sae103-php tar -czvf Docs.tar.gz "DOC_TECH-$version.pdf" #"DOC_USER-$version.pdf"


 docker cp sae103-forever:/work/Docs.tar.gz ./

docker run --rm -v sae103:/work sae103-php ls -lt ./
 # Arrêt du conteneur
 docker stop sae103-forever
 docker rm sae103-forever

# # Suppression du volume sae103
 docker volume rm sae103